### PR TITLE
24 register screen

### LINKED ISSUE #24: Register screen
Add RegisterScreen component
RegisterScreen should only be available in the navigation stack if the user is not logged in
Send user data to the Backend API
Handle errors if register fails
Handle redirection to Login screen (or auto-login - TBD)

### PR DESCRIPTION
**Pull request by pawap90**
Register a new user
Closes #24

### CODE REVIEW

File: src/services/AccountService.js [hunk 1]
```diff
@@ -91,6 +92,47 @@ export default class AccountService {
 		}
 	}
 
+	/**
+	 * Register a new account.
+	 * @param {RegisterModel} accountModel Register data
```
Comment (mauro-codes) [inline src/services/AccountService.js:97]: registerModel instead of accountModel
